### ISSUE TITLE
cardlist idird

### ISSUE THREAD

**Issue by msrx111** [Schimmelreiter/oscam-smod#49]
Wenn ich baue dann kommt folgender Fehler bzw Warnung:

cardlist.c:59:16: warning: ‘idird’ defined but not used [-Wunused-variable]

Wenn ich das binary dann mit einer HD03/04 Karte starte wird die Karte nicht gelesen, weil die idird fehlt. Wenn ich das dann in der oscam.server eintrage funktioniert es. Aber das ist ja nun nicht Sinn der Sache...

Gruß

Martin

**Comment by WXbet** [comment]
Hast du alle notwendigen Informationen in der cardlist.c? Wenn nicht, muss der Reader (incl. idird) normal in oscam konfiguriert werden.

**Comment by msrx111** [comment]
DIe idird steht in der cardlist. Und wenn ich dann baue kommt der o.a. Fehler, und wenn ich die oscam starte liest er die Karte nicht ein ,weil alle Keys außer der idird drin sind. Erst wenn ich die idird manuell nachtrage läuft die Karte. Aber genau das selbe steht oben schon.

**Comment by msrx111** [comment]
gerade noch mal neu ausgecheckt. cardlist.c reinkopiert:

cardlist.c:69:16: warning: ‘maxtv_idird’ defined but not used [-Wunused-variable]
 static uint8_t maxtv_idird[4] = {0xFF,0xFF,0xFF,0xFF};
                ^~~~~~~~~~~
cardlist.c:59:16: warning: ‘idird’ defined but not used [-Wunused-variable]
 static uint8_t idird[4] = {0xFF,0xFF,0xFF,0xFF};
                ^~~~~

Selber Fehler. Alles Keys sind in der Cardlist drin. Aber mit der idird aus der cardlist kann er nichts anfangen und beim binary fehlt sie dann im Gegensatz zu allen anderen Keys....

**Comment by WXbet** [comment]
stb pn

**Comment by msrx111** [comment]
Kann geschlossen werden, sorry. Habe jetzt nochmal neu ausgecheckt und jetzt baut es ohne Fehler. Habe mir aus dem FF Forum den cardlist patch besorgt und damit geht es jetzt anscheinend.... Aber danke für deine Hilfe. So musste ich mich nochmal intensiv damit befassen und wieder etwas gelernt.
