### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by mfu-mcosys** [Schimmelreiter/oscam-smod#5]
current master ends up with this error:

`csctapi/cardlist.c: In function ‘findatr’:
csctapi/cardlist.c:192:17: error: ‘struct s_reader’ has no member named ‘data50’
    memcpy(reader->data50, data50,  80);
                 ^~
csctapi/cardlist.c:193:17: error: ‘struct s_reader’ has no member named ‘mod50’
    memcpy(reader->mod50,  mod50,  80);
                 ^~
csctapi/cardlist.c:194:17: error: ‘struct s_reader’ has no member named ‘key60’
    memcpy(reader->key60,  key60,  96);
                 ^~
csctapi/cardlist.c:195:17: error: ‘struct s_reader’ has no member named ‘exp60’
    memcpy(reader->exp60,  exp60,  96);
                 ^~
csctapi/cardlist.c:196:17: error: ‘struct s_reader’ has no member named ‘mod1’
    memcpy(reader->mod1,   mod1, 112);
                 ^~
csctapi/cardlist.c:197:19: error: ‘struct s_reader’ has no member named ‘nuid’; did you mean ‘prid’?
    memcpy(reader->nuid,   max_nuid,   4);
                   ^~~~
                   prid
csctapi/cardlist.c:198:17: error: ‘struct s_reader’ has no member named ‘cwekey0’
    memcpy(reader->cwekey0, max_cwpk,  16);
                 ^~
csctapi/cardlist.c:200:12: error: ‘struct s_reader’ has no member named ‘data50_length’; did you mean ‘boxkey_length’?
    reader->data50_length =  80;
            ^~~~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:201:12: error: ‘struct s_reader’ has no member named ‘mod50_length’; did you mean ‘boxkey_length’?
    reader->mod50_length  =  80;
            ^~~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:202:12: error: ‘struct s_reader’ has no member named ‘key60_length’; did you mean ‘boxkey_length’?
    reader->key60_length  =  96;
            ^~~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:203:12: error: ‘struct s_reader’ has no member named ‘exp60_length’; did you mean ‘boxkey_length’?
    reader->exp60_length  =  96;
            ^~~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:204:12: error: ‘struct s_reader’ has no member named ‘mod1_length’; did you mean ‘boxkey_length’?
    reader->mod1_length   = 112;
            ^~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:205:12: error: ‘struct s_reader’ has no member named ‘nuid_length’; did you mean ‘boxkey_length’?
    reader->nuid_length   =   4;
            ^~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:206:12: error: ‘struct s_reader’ has no member named ‘cwekey0_length’; did you mean ‘boxkey_length’?
    reader->cwekey0_length =  16;
            ^~~~~~~~~~~~~~
            boxkey_length
csctapi/cardlist.c:229:18: error: ‘struct s_reader’ has no member named ‘data50’
     memcpy(reader->data50,  data50,      80);
                  ^~
csctapi/cardlist.c:230:18: error: ‘struct s_reader’ has no member named ‘mod50’
     memcpy(reader->mod50,   mod50,       80);
                  ^~
csctapi/cardlist.c:231:18: error: ‘struct s_reader’ has no member named ‘mod1’
     memcpy(reader->mod1,    mod1,       112);
                  ^~
csctapi/cardlist.c:232:20: error: ‘struct s_reader’ has no member named ‘nuid’; did you mean ‘prid’?
     memcpy(reader->nuid,    hd_nuid,      4);
                    ^~~~
                    prid
csctapi/cardlist.c:233:18: error: ‘struct s_reader’ has no member named ‘cwekey0’
     memcpy(reader->cwekey0, hd_cwpk,     16);
                  ^~
csctapi/cardlist.c:234:18: error: ‘struct s_reader’ has no member named ‘key3588’
     memcpy(reader->key3588, hd_key3588, 136);
                  ^~
csctapi/cardlist.c:235:18: error: ‘struct s_reader’ has no member named ‘idird’
     memcpy(reader->idird,   hd_idird,     4);
                  ^~
csctapi/cardlist.c:237:13: error: ‘struct s_reader’ has no member named ‘data50_length’; did you mean ‘boxkey_length’?
     reader->data50_length =   80;
             ^~~~~~~~~~~~~
             boxkey_length
csctapi/cardlist.c:238:13: error: ‘struct s_reader’ has no member named ‘mod50_length’; did you mean ‘boxkey_length’?
     reader->mod50_length  =   80;
             ^~~~~~~~~~~~
             boxkey_length
csctapi/cardlist.c:239:13: error: ‘struct s_reader’ has no member named ‘mod1_length’; did you mean ‘boxkey_length’?
     reader->mod1_length   =  112;
             ^~~~~~~~~~~
             boxkey_length
csctapi/cardlist.c:240:13: error: ‘struct s_reader’ has no member named ‘nuid_length’; did you mean ‘boxkey_length’?
     reader->nuid_length   =    4;
             ^~~~~~~~~~~
             boxkey_length
csctapi/cardlist.c:241:13: error: ‘struct s_reader’ has no member named ‘cwekey0_length’; did you mean ‘boxkey_length’?
     reader->cwekey0_length =  16;
             ^~~~~~~~~~~~~~
             boxkey_length
csctapi/cardlist.c:242:13: error: ‘struct s_reader’ has no member named ‘key3588_length’; did you mean ‘des_key_length’?
     reader->key3588_length = 136;
             ^~~~~~~~~~~~~~
             des_key_length
csctapi/cardlist.c:243:13: error: ‘struct s_reader’ has no member named ‘idird_length’; did you mean ‘boxkey_length’?
     reader->idird_length =     4;
             ^~~~~~~~~~~~
             boxkey_length
CC	csctapi/protocol_t0.c
At top level:
csctapi/cardlist.c:19:19: warning: ‘cmd0eprov’ defined but not used [-Wunused-const-variable=]
 static const char cmd0eprov[3]     = { "\x00" };
                   ^~~~~~~~~
csctapi/cardlist.c:18:19: warning: ‘mod2’ defined but not used [-Wunused-const-variable=]
 static const char mod2[113]        = { "\x00" };
                   ^~~~
csctapi/cardlist.c:16:19: warning: ‘key3310’ defined but not used [-Wunused-const-variable=]
 static const char key3310[17]      = { "\x00" };
                   ^~~~~~~
csctapi/cardlist.c:15:19: warning: ‘key3460’ defined but not used [-Wunused-const-variable=]
 static const char key3460[97]      = { "\x00" };
                   ^~~~~~~
make[1]: *** [Makefile:455: build/x86_64-pc-linux-gnu-ssl-libusb/csctapi/cardlist.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:409: all] Error 2`

This is the ENV (if it helps)

> make -j8 OSCAM_BIN=$(BINDIR)/oscam LIST_SMARGO_BIN=$(BINDIR)/list_smargo CONF_DIR=/etc/oscam USE_LIBUSB=1 CC=x86_64-pc-linux-gnu-gcc CXX=x86_64-pc-linux-gnu-g++ 
> +-------------------------------------------------------------------------------
> | OSCam ver: smod rev: 11546 target: x86_64-pc-linux-gnu-ssl-libusb
> | Tools:
> |  CROSS    = 
> |  CC       = x86_64-pc-linux-gnu-gcc
> | Settings:
> |  CONF_DIR = /etc/oscam
> |  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
> |  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
> |  CFLAGS   = -O2 -pipe -march=native -fexpensive-optimizations -mmmx -msse -msse2 -msse3 -DWITH_SSL=1 -DWITH_LIBCRYPTO=1 -DWITH_LIBUSB=1
> |  LDFLAGS  = -Wl,--gc-sections -DWITH_SSL=1 -DWITH_LIBCRYPTO=1 -DWITH_LIBUSB=1
> |  LIBS     = -lssl -lcrypto -lusb-1.0 -lrt -lm -lpthread -ldl
> |  UseFlags = USE_SSL=1 USE_LIBCRYPTO=1 USE_LIBUSB=1
> | Config:
> |  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY WITH_SSL HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK LEDSUPPORT WITH_EMU
> |  Protocols: CAMD33 CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SERIAL CONSTCW PANDORA GHTTP
> |  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT DGCRYPT
> |  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO STINGER DRECAS SMART
> |  Compiler : x86_64-pc-linux-gnu-gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0
> |  Config   : build/x86_64-pc-linux-gnu-ssl-libusb/config.mak
> |  Binary   : Distribution/oscam

**Comment by Schimmelreiter** [comment]
You are missing Reader NAGRA_MERLIN
Readers need NAGRA_MERLIN to have these members.

**Comment by mfu-mcosys** [comment]
U are right. :)
This happens if u just pull new versions from GIT without checking for new flags. :)
THX!

**Comment by Schimmelreiter** [comment]
Actually it is an issue anyways: I should add ifdefs to cardlist.c to avoid unsupported cards resp. card with unsupported systems from being configured.

**Comment by Schimmelreiter** [comment]
Should be fixed now, tnx WxBet/ds777 :)
