### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MegaV0lt** [Schimmelreiter/oscam-smod#50]
today my first try:

+-------------------------------------------------------------------------------
| OSCam ver: smod rev: git+2181+d6bbc6d target: x86_64-linux-gnu
| Tools:
|  CROSS    = 
|  CC       = gcc
| Settings:
|  CONF_DIR = /usr/local/etc
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -fexpensive-optimizations -mmmx -msse -msse2 -msse3
|  LDFLAGS  = -Wl,--gc-sections
|  LIBS     = -lm -lpthread -ldl
|  UseFlags = 
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK LCDSUPPORT IPV6SUPPORT WITH_EMU WITH_CARDLIST
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA NAGRA_MERLIN IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG STREAMGUARD JET BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX
|  Compiler : gcc (Debian 8.3.0-6) 8.3.0
|  Config   : build/x86_64-linux-gnu/config.mak
|  Binary   : Distribution/oscam-smod+git+2181+d6bbc6d-x86_64-linux-gnu
+-------------------------------------------------------------------------------
HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 474144 template bytes into 194723 bytes. 279421 saved bytes (58.93%).
CC	cscrypt/aes.c
CC	cscrypt/bn_add.c
CC	cscrypt/bn_asm.c
CC	cscrypt/bn_ctx.c
CC	cscrypt/bn_div.c
CC	cscrypt/bn_exp.c
CC	cscrypt/bn_lib.c
CC	cscrypt/bn_mul.c
CC	cscrypt/bn_print.c
CC	cscrypt/bn_shift.c
CC	cscrypt/bn_sqr.c
CC	cscrypt/bn_word.c
CC	cscrypt/mem.c
CC	cscrypt/des.c
CC	cscrypt/jet_twofish.c
CC	cscrypt/jet_dh.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_ecb.c
CC	cscrypt/i_skey.c
CC	cscrypt/md5.c
CC	cscrypt/rc6.c
CC	cscrypt/sha1.c
CC	cscrypt/mdc2.c
CC	cscrypt/fast_aes.c
CC	cscrypt/sha256.c
CC	cardlist.c
CC	csctapi/atr.c
CC	csctapi/icc_async.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	csctapi/protocol_t1.c
CC	csctapi/ifd_phoenix.c
CC	minilzo/minilzo.c
CC	module-anticasc.c
CC	module-cacheex.c
CC	module-camd35-cacheex.c
CC	module-camd35.c
CC	module-cccam-cacheex.c
CC	module-cccam.c
CC	module-cccshare.c
CC	module-constcw.c
CC	module-emulator.c
CC	module-emulator-osemu.c
CC	module-emulator-streamserver.c
CC	module-emulator-biss.c
CC	module-emulator-cryptoworks.c
CC	module-emulator-director.c
CC	module-emulator-irdeto.c
CC	module-emulator-nagravision.c
CC	module-emulator-powervu.c
CC	module-emulator-viaccess.c
CC	ffdecsa/ffdecsa.c
CC	module-csp.c
CC	module-cw-cycle-check.c
CC	module-dvbapi-chancache.c
CC	module-dvbapi.c
CC	module-gbox-helper.c
CC	module-gbox-sms.c
CC	module-gbox-remm.c
CC	module-gbox-cards.c
CC	module-gbox.c
CC	module-ird-guess.c
CC	module-lcd.c
CC	module-monitor.c
CC	module-newcamd.c
CC	module-newcamd-des.c
CC	module-pandora.c
CC	module-ghttp.c
CC	module-radegast.c
CC	module-scam.c
CC	module-serial.c
CC	module-stat.c
CC	module-webif-lib.c
CC	module-webif-tpl.c
CC	module-webif.c
CC	webif/pages.c
CC	reader-common.c
CC	reader-bulcrypt.c
CC	reader-conax.c
CC	reader-cryptoworks.c
CC	reader-dgcrypt.c
CC	reader-dre.c
CC	reader-dre-cas.c
CC	reader-dre-common.c
CC	reader-dre-st20.c
CC	reader-griffin.c
CC	reader-irdeto.c
CC	reader-nagra-common.c
CC	reader-nagra.c
CC	reader-nagracak7.c
CC	reader-seca.c
CC	reader-tongfang.c
CC	reader-streamguard.c
CC	reader-jet.c
CC	reader-viaccess.c
CC	reader-videoguard-common.c
CC	reader-videoguard1.c
CC	reader-videoguard12.c
CC	reader-videoguard2.c
CC	oscam-aes.c
CC	oscam-array.c
CC	oscam-hashtable.c
CC	oscam-cache.c
CC	oscam-chk.c
CC	oscam-client.c
CC	oscam-conf.c
CC	oscam-conf-chk.c
CC	oscam-conf-mk.c
CC	oscam-config-null.c
oscam-config-null.c: In function ‘conf_file’:
oscam-config-null.c:103:7: warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
       strncpy(buffer, server_str, strlen(server_str));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
oscam-config-null.c:86:8: warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
        strncpy(buffer, server_str, strlen(server_str));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC	oscam-config-account.c
CC	oscam-config-global.c
CC	oscam-config-reader.c
CC	oscam-config.c
CC	oscam-ecm.c
CC	oscam-emm.c
CC	oscam-emm-cache.c
CC	oscam-failban.c
CC	oscam-files.c
CC	oscam-garbage.c
CC	oscam-lock.c
CC	oscam-log.c
CC	oscam-log-reader.c
CC	oscam-net.c
CC	oscam-llist.c
CC	oscam-reader.c
CC	oscam-simples.c
CC	oscam-string.c
CC	oscam-time.c
CC	oscam-work.c
CC	oscam.c
CONF	build/x86_64-linux-gnu/config.c
LINK	Distribution/oscam-smod+git+2181+d6bbc6d-x86_64-linux-gnu.debug
/usr/bin/ld: build/x86_64-linux-gnu/module-emulator-biss.o: in function `parse_session_data':
/usr/local/src/oscam-smod.git/module-emulator-biss.c:677: undefined reference to `RSA_private_decrypt'
/usr/bin/ld: build/x86_64-linux-gnu/module-emulator-biss.o: in function `biss_read_pem':
/usr/local/src/oscam-smod.git/module-emulator-biss.c:835: undefined reference to `PEM_read_RSAPrivateKey'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:860: undefined reference to `i2d_RSA_PUBKEY'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:869: undefined reference to `EVP_MD_CTX_new'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:875: undefined reference to `EVP_sha256'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:875: undefined reference to `EVP_DigestInit_ex'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:876: undefined reference to `EVP_DigestUpdate'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:877: undefined reference to `EVP_DigestFinal_ex'
/usr/bin/ld: /usr/local/src/oscam-smod.git/module-emulator-biss.c:878: undefined reference to `EVP_MD_CTX_free'
/usr/bin/ld: build/x86_64-linux-gnu/reader-nagracak7.o: in function `CreateRSAPair60':
/usr/local/src/oscam-smod.git/reader-nagracak7.c:692: undefined reference to `BN_mod_inverse'
/usr/bin/ld: build/x86_64-linux-gnu/reader-nagracak7.o: in function `CreateRSAPair68':
/usr/local/src/oscam-smod.git/reader-nagracak7.c:746: undefined reference to `BN_mod_inverse'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:439: Distribution/oscam-smod+git+2181+d6bbc6d-x86_64-linux-gnu.debug] Fehler 1
make: *** [Makefile:411: all] Fehler 2

Maybe config-related?

**Comment by WXbet** [comment]
Please try: apt-get install libssl-dev
Maybe its an SSL-related error.

**Comment by MegaV0lt** [comment]
Already installed:
```
[~] # apt install libssl-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libssl-dev ist schon die neueste Version (1.1.1d-0+deb10u2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

```

**Comment by MegaV0lt** [comment]
I addes  "With OpenSSL" in the config. Now it builds correct.

A few warnings :
```
CC	oscam-config-null.c
oscam-config-null.c: In function ‘conf_file’:
oscam-config-null.c:103:7: warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
       strncpy(buffer, server_str, strlen(server_str));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
oscam-config-null.c:86:8: warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
        strncpy(buffer, server_str, strlen(server_str));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC	oscam-config-account.c
```
