### ISSUE TITLE
hd02 + hd04

### ISSUE THREAD

**Issue by mfu-mcosys** [Schimmelreiter/oscam-smod#6]
Seems like with the current git version (r11546) there is a problem with hd02 and hd04?

Because after upgrade oscam cant read my hd02 and the HD04 wasnt working too.
After testing against current svn version..everything is fine.
Maybe a new pull? :)

**Comment by WXbet** [comment]
Here, hd02 and hd04 are working with the latest smod. If you build your own smod, you need the correct keys in your config. For further help, please provide card initialization log.

**Comment by mfu-mcosys** [comment]
2019/11/03 10:45:06 44A35C84 r   (reader) AL05HSPS [mouse] Resync error: readtimeouts 0/0 (max/min) us, writetimeouts 0/0 (max/min) us
2019/11/03 10:45:07 399FF7C0 r   (reader) AL03VAMD [mouse] card is not responding to CMD02/E - check your data
2019/11/03 10:45:07 399FF7C0 r   (reader) AL03VAMD [mouse] card system not supported
2019/11/03 10:45:07 399FF7C0 r   (reader) AL03VAMD [mouse] Normal mode failed, reverting to Deprecated Mode
2019/11/03 10:45:08 44A35C84 r   (reader) AL05HSPS [mouse] T1 Resync command error, trying to reactivate!
2019/11/03 10:45:08 399FF7C0 r   (reader) AL03VAMD [mouse] ATR: 3F FF 95 00 FF 91 81 71 FE 57 00 44 4E 41 53 50 34 32 30 20 52 65 76 53 36 30 17 
2019/11/03 10:45:08 399FF7C0 r   (reader) AL03VAMD [mouse] Astra HD+ HD04 recognized
2019/11/03 10:45:09 44A35C84 r   (reader) AL05HSPS [mouse] ATR: 3F FF 95 00 FF 91 81 71 A0 47 00 44 4E 41 53 50 31 38 30 20 4D 65 72 30 30 30 28 
2019/11/03 10:45:09 44A35C84 r   (reader) AL05HSPS [mouse] Astra HD+ HD02 recognized
2019/11/03 10:45:09 44A35C84 r   (reader) AL05HSPS [mouse] Setting baudrate to 111600 bps
2019/11/03 10:45:09 44A35C84 r   (reader) AL05HSPS [mouse] card system not supported
2019/11/03 10:45:09 44A35C84 r   (reader) AL05HSPS [mouse] Normal mode failed, reverting to Deprecated Mode
2019/11/03 10:45:10 44A35C84 r   (reader) AL05HSPS [mouse] ATR: 3F FF 95 00 FF 91 81 71 A0 47 00 44 4E 41 53 50 31 38 30 20 4D 65 72 30 30 30 28 
2019/11/03 10:45:10 44A35C84 r   (reader) AL05HSPS [mouse] Astra HD+ HD02 recognized
2019/11/03 10:45:11 399FF7C0 r   (reader) AL03VAMD [mouse] Warning: Card returned error on setting ifsd value to 251
2019/11/03 10:45:11 399FF7C0 r   (reader) AL03VAMD [mouse] detected card in CAK7 mode
2019/11/03 10:45:12 44A35C84 r   (reader) AL05HSPS [mouse] Warning: Card returned error on setting ifsd value to 160
2019/11/03 10:45:12 399FF7C0 r   (reader) AL03VAMD [mouse] Rom revision: DNASP420 RevS60
2019/11/03 10:45:13 44A35C84 r   (reader) AL05HSPS [mouse] detect native nagra card
2019/11/03 10:45:15 44A35C84 r   (reader) AL05HSPS [mouse] Resync error: readtimeouts 0/0 (max/min) us, writetimeouts 0/0 (max/min) us
2019/11/03 10:45:17 44A35C84 r   (reader) AL05HSPS [mouse] T1 Resync command error, trying to reactivate!
2019/11/03 10:45:18 44A35C84 r   (reader) AL05HSPS [mouse] ATR: 3F FF 95 00 FF 91 81 71 A0 47 00 44 4E 41 53 50 31 38 30 20 4D 65 72 30 30 30 28 
2019/11/03 10:45:18 44A35C84 r   (reader) AL05HSPS [mouse] Astra HD+ HD02 recognized
2019/11/03 10:45:18 44A35C84 r   (reader) AL05HSPS [mouse] Setting baudrate to 111600 bps
2019/11/03 10:45:21 44A35C84 r   (reader) AL05HSPS [mouse] Resync error: readtimeouts 0/0 (max/min) us, writetimeouts 0/0 (max/min) us
2019/11/03 10:45:22 399FF7C0 r   (reader) AL03VAMD [mouse] card is not responding to CMD02/E - check your data
2019/11/03 10:45:22 399FF7C0 r   (reader) AL03VAMD [mouse] card system not supported
2019/11/03 10:45:22 399FF7C0 r   (reader) AL03VAMD [mouse] THIS WAS A FAILED START ATTEMPT No 1 out of max allotted of 1
2019/11/03 10:45:22 399FF7C0 r   (reader) AL03VAMD [mouse] card initializing error



Same config works perfect with oscam from svn, so i guess is there is something wrong.

**Comment by WXbet** [comment]
I think your keys are not present. You need the correct keys in https://github.com/Schimmelreiter/oscam-smod/blob/master/csctapi/cardlist.c (not in config, sorry) for smod.

**Comment by mfu-mcosys** [comment]
mod1                          = 9D....E63
data50                        = B67...592
mod50                         = DB9E...4D5
key60                         = 99E9....25EB
exp60                         = 26A6...1421
nuid                          = 84...1E
cwekey                        = 1B...C6

But this should be the correct keys?

**Comment by WXbet** [comment]
Looks correct, but missing some.

You need in cardlist.c (replaced with the correct values):

**for HD02**
```
static const char hd_boxkey[9]     = { "\x01\x02\...\x02\x01" };
static const char hd_rsakey[129]   = { "\x01\x02\...\x02\x01" };
```

**for HD04**
```
static const char data50[81]       = { "\x01\x02\...\x02\x01" };
static const char mod50[81]        = { "\x01\x02\...\x02\x01" };
static const char mod1[113]        = { "\x01\x02\...\x02\x01" };
static const char hd_nuid[5]       = { "\x01\x02\...\x02\x01" };
static const char hd_cwpk[17]      = { "\x01\x02\...\x02\x01" };
static const char hd_key3588[137]  = { "\x01\x02\...\x02\x01" };
static const char hd_idird[5]      = { "\x01\x02\...\x02\x01" };
```

Or you use the binaries from here: https://www.digital-eliteboard.com/threads/softcam-feed-fuer-openatv-und-andere-oe-a-distros-wie-openhdf-teamblue-openvix.476016/

**Comment by WXbet** [comment]
@mfu-mcosys: Please close this issue if your cards are working now.

**Comment by mfu-mcosys** [comment]
Oh i forget :/
I switched from smod to svn, because i wasnt able to use the hd04 with smod.
SVN and a cak7 patch...everything fine.

So ok, i will close the issue :)
