### ISSUE TITLE
(emu) icam_send_to_radegast: Send failure, (-) -- Skipped 1 duplicated log lines --

### ISSUE THREAD

**Issue by Suedschwede66** [Schimmelreiter/oscam-smod#61]
Everything runs very well except for the small optical error in the log.

`2022/12/31 13:16:27 1D9E4D23 c      (ecm) DVBApi (0x8D@000000/00F5/008B/B7:925D136C592BCC4DFDAE07E05587CF92): found (174 ms) by Icam - xxx xxxxxx
2022/12/31 13:16:33 00000000        (emu) icam_send_to_radegast: Send failure
2022/12/31 13:16:34 1D9E4D23 c        (-) -- Skipped 1 duplicated log lines --
2022/12/31 13:16:34 1D9E4D23 c      (ecm) DVBApi (09xD@000000/00F5/008B/B7:2CB17ED9B7F1E2993FB76E187CC9DDA0): found (393 ms) by Icam - xxx xxxxxx
2022/12/31 13:16:40 00000000        (emu) icam_send_to_radegast: Send failure
2022/12/31 13:16:41 1D9E4D23 c        (-) -- Skipped 1 duplicated log lines --
2022/12/31 13:16:41 1D9E4D23 c      (ecm) DVBApi (09xD@000000/00F5/008B/B7:5B4A894E2B21D18EBAC7BE35CDB67500): found (184 ms) by Icam - xxx xxxxxx
2022/12/31 13:16:47 00000000        (emu) icam_send_to_radegast: Send failure
2022/12/31 13:16:48 1D9E4D23 c        (-) -- Skipped 1 duplicated log lines --
2022/12/31 13:16:48 1D9E4D23 c      (ecm) DVBApi (09xD@000000/00F5/008B/B7:3C573646A4E16EC0BEA759DD02A39AB0): found (178 ms) by Icam - xxx xxxxxx
2022/12/31 13:16:54 00000000        (emu) icam_send_to_radegast: Send failure
2022/12/31 13:16:55 1D9E4D23 c        (-) -- Skipped 1 duplicated log lines --
2022/12/31 13:16:55 1D9E4D23 c      (ecm) DVBApi (09xD@000000/00F5/008B/B7:80C0FA28194B3793A9D5C1B3A851C65D): found (177 ms) by Icam - xxx xxxxxx
2022/12/31 13:17:01 00000000        (emu) icam_send_to_radegast: Send failure
2022/12/31 13:17:02 1D9E4D23 c        (-) -- Skipped 1 duplicated log lines --
2022/12/31 13:17:02 1D9E4D23 c      (ecm) DVBApi (09xD@000000/00F5/008B/B7:81E1952804E50FE630FBBF3DCC524A52): found (181 ms) by Icam - xxx xxxxxx
2022/12/31 13:17:09 00000000        (emu) icam_send_to_radegast: Send failure
2022/12/31 13:17:09 1D9E4D23 c        (-) -- Skipped 1 duplicated log lines --
2022/12/31 13:17:09 1D9E4D23 c      (ecm) DVBApi (09xD@000000/00F5/008B/B7:811041B7823DC250386412A070BAF3EF): found (173 ms) by Icam - xxx xxxxxx`

**Comment by Suedschwede66** [comment]
Absolutely the same setup on both devices, different log output.
**AX HD51**
![HD51](https://user-images.githubusercontent.com/56753772/210137687-9947946b-aed1-448d-baa6-b0ad9a4e7352.png)
**SF8008**
![SF8008](https://user-images.githubusercontent.com/56753772/210137689-b03e1d60-fad1-47de-b6f7-b2395a136b2a.png)

**Comment by Schimmelreiter** [comment]
I'm currently investigating this issue.

**Comment by Suedschwede66** [comment]
I built and tested [OSCam smod git+2395+(Trunk r11718), the log problem is now also ok on the SF8008.
Emu also tested on 40.5W PowerVu Autoupdate is ok, Tandberg Emu is ok too.
Thank you and happy new year.

![SF8008_1](https://user-images.githubusercontent.com/56753772/210148695-1883ab0e-1050-4c67-bc09-214ba141d2e6.png)
